jobs:
  keymap-drawer:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Install uv with caching
      uses: astral-sh/setup-uv@main
      with:
        enable-cache: 'true'
    - name: Install keymap-drawer
      run: uv tool install keymap-drawer
    - name: Run keymap-drawer
      run: keymap draw ./keymap-drawer/tltr.yml 1> assets/tltr.svg
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Push to repo
      run: 'git config --global user.name "GitHub Actions Bot"

        git config --global user.email bot@github.com

        git add .

        git commit -m "chore: update keymap-drawer assets"

        git push origin master

        '
    timeout-minutes: 30
'on':
  pull_request:
    branches:
    - master
    paths:
    - keymap-drawer/**
  push:
    branches:
    - master
    paths:
    - keymap-drawer/**
  workflow_dispatch: {}
